### ISSUE TITLE
Assignment 3 - Missing Bold and Italic text

### ISSUE THREAD

**Issue by ProfPollati** [Bloomfield-FA15-CAT238/FirstRepo-RobinsonKeaun#1]
Part of the assignment was to include **_bold and italic_** text.

**Comment by Keaun** [comment]
Bold and italic is in line 7, quote "I think this is you get the idea"
where this is is in italics in the sentence whilst the whole sentence is in
bold

**Comment by ProfPollati** [comment]
Don't know why I missed that... I will adjust your grade!
