### ISSUE TITLE
Assignment 3 - Missing Ordered list

### ISSUE THREAD

**Issue by ProfPollati** [Bloomfield-FA15-CAT238/FirstRepo-RobinsonKeaun#2]
You needed to include an ordered list which has steps in like
1. Step one
2. Step two
3. Step three
4. and so on...

**Comment by Keaun** [comment]
My ordered list is 1 with the unordered list nested in it and then 2 with
the link to the picture

**Comment by ProfPollati** [comment]
Sorry I missed that, I will adjust your grade!
